# Site settings
title: Gregging
email: greg.cerveny@gmail.com
description: "What little I know about computers, music, and the infinite universe."
baseurl: "/gregging"
url: "http://gregcerveny.com"
timezone: America/Chicago
username: gmcerveny

# Build settings
markdown: kramdown
permalink: pretty
